## linear algebra with numpy


### Dot product :

- Dot Product is a way to multiply two vectors.

- It gives a single scalar value (not a vector or matrix).

### numpy method to get dot product 

- ```np.dot()```
- using ```@```

- both do same thing (for 1D and 2D array)

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Method 1
print(np.dot(a, b))  # ➝ 1*4 + 2*5 + 3*6 = 32

# Method 2 (preferred shortcut)
print(a @ b)         # ➝ 32


32
32


dot poduct condition 
- 1D * 1D
- 2D * 2D
- 3D * 3D  

example with 2D array (matrix dot product)

In [2]:
A = np.array([[1, 2],
              [3, 4]])     # Shape (2, 2)

B = np.array([[5, 6],
              [7, 8]])     # Shape (2, 2)

C = np.dot(A, B)
print(C)


[[19 22]
 [43 50]]


example in 3D array 

In [3]:
import numpy as np

a = np.array([[[1, 2],
               [3, 4]]])        # Shape: (1, 2, 2)

b = np.array([[[5, 6],
               [7, 8]]])        # Shape: (1, 2, 2)

result = np.dot(a, b)
print(result)
print("Shape:", result.shape)


[[[[19 22]]

  [[43 50]]]]
Shape: (1, 2, 1, 2)


In [4]:
# using @ module 
a = np.random.randint(1, 10, (2, 3, 4))  # 2 matrices of 3×4
b = np.random.randint(1, 10, (2, 4, 5))  # 2 matrices of 4×5

result = a @ b
print("Shape:", result.shape)


Shape: (2, 3, 5)


### matrix multiplication 

- Matrix multiplication is not element-wise multiplication.

- It’s a special way to combine two matrices where the columns of the first are matched with the rows of the second.

- Condition to multiply:
  - If
  - Matrix A → shape (m × n)
  - Matrix B → shape (n × p)
  - Then result → shape (m × p)

using ```np.matmul``` or ```@``` you can multiply two matrices 

In [5]:
# example 2D matrix multiplication 
import numpy as np

A = np.array([[1, 2],
              [3, 4]])     # Shape: (2, 2)

B = np.array([[5, 6],
              [7, 8]])     # Shape: (2, 2)

result = np.matmul(A, B)
# OR use A @ B
print(result)


[[19 22]
 [43 50]]


In [6]:
# example 3D matrix multiplication
A = np.random.randint(1, 5, (2, 3, 4))  # Two 3×4 matrices
B = np.random.randint(1, 5, (2, 4, 2))  # Two 4×2 matrices

C = np.matmul(A, B)  # or A @ B
print(C.shape)


(2, 3, 2)


### Determinant and inverse in numpy 

- These are essential concepts in linear algebra, especially when solving systems of equations or checking if a matrix is invertible.


#### Determinant ?

- determinant is a single number calculated from square matrix 

- Why is it important?

    - It tells us whether a matrix is invertible.

    - If det(A) ≠ 0 → matrix is invertible ✅

    - If det(A) = 0 → matrix is singular ❌ (no inverse) 

In [ ]:
# example of 2x2 matrix 
import numpy as np

A = np.array([[2, 3],
              [1, 4]])

det_A = np.linalg.det(A)
print("Determinant:", det_A)


 # What is the Inverse of a Matrix?

- The inverse of a matrix A is another matrix A⁻¹ 
- Where I is the identity matrix.

- In simpler words: it's like division in matrix world.
   A⁻¹ “undoes” what A does.

In [7]:
A = np.array([[2, 3],
              [1, 4]])

inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)


Inverse of A:
 [[ 0.8 -0.6]
 [-0.2  0.4]]


example of 3x3 matrix example 

In [8]:
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

inv_A = np.linalg.inv(A)
print("Inverse:\n", inv_A)


Inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
