## linear algebra with numpy


### Dot product :

- Dot Product is a way to multiply two vectors.

- It gives a single scalar value (not a vector or matrix).

### numpy method to get dot product 

- ```np.dot()```
- using ```@```

- both do same thing (for 1D and 2D array)

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Method 1
print(np.dot(a, b))  # ➝ 1*4 + 2*5 + 3*6 = 32

# Method 2 (preferred shortcut)
print(a @ b)         # ➝ 32


32
32


dot poduct condition 
- 1D * 1D
- 2D * 2D
- 3D * 3D  

example with 2D array (matrix dot product)

In [2]:
A = np.array([[1, 2],
              [3, 4]])     # Shape (2, 2)

B = np.array([[5, 6],
              [7, 8]])     # Shape (2, 2)

C = np.dot(A, B)
print(C)


[[19 22]
 [43 50]]


example in 3D array 

In [3]:
import numpy as np

a = np.array([[[1, 2],
               [3, 4]]])        # Shape: (1, 2, 2)

b = np.array([[[5, 6],
               [7, 8]]])        # Shape: (1, 2, 2)

result = np.dot(a, b)
print(result)
print("Shape:", result.shape)


[[[[19 22]]

  [[43 50]]]]
Shape: (1, 2, 1, 2)


In [4]:
# using @ module 
a = np.random.randint(1, 10, (2, 3, 4))  # 2 matrices of 3×4
b = np.random.randint(1, 10, (2, 4, 5))  # 2 matrices of 4×5

result = a @ b
print("Shape:", result.shape)


Shape: (2, 3, 5)
