## linear algebra with numpy

- Linear algebra involves operations on vectors and matrices — like multiplication, inverses, transposes, solving systems of equations, etc.

NumPy provides many linear algebra functions through:


In [1]:
import numpy.linalg

### Dot product :

- Dot Product is a way to multiply two vectors.

- It gives a single scalar value (not a vector or matrix).

### numpy method to get dot product 

- ```np.dot()```
- using ```@```

- both do same thing (for 1D and 2D array)

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Method 1
print(np.dot(a, b))  # ➝ 1*4 + 2*5 + 3*6 = 32

# Method 2 (preferred shortcut)
print(a @ b)         # ➝ 32


32
32


dot poduct condition 
- 1D * 1D
- 2D * 2D
- 3D * 3D  

example with 2D array (matrix dot product)

In [2]:
A = np.array([[1, 2],
              [3, 4]])     # Shape (2, 2)

B = np.array([[5, 6],
              [7, 8]])     # Shape (2, 2)

C = np.dot(A, B)
print(C)


[[19 22]
 [43 50]]


example in 3D array 

In [3]:
import numpy as np

a = np.array([[[1, 2],
               [3, 4]]])        # Shape: (1, 2, 2)

b = np.array([[[5, 6],
               [7, 8]]])        # Shape: (1, 2, 2)

result = np.dot(a, b)
print(result)
print("Shape:", result.shape)


[[[[19 22]]

  [[43 50]]]]
Shape: (1, 2, 1, 2)


In [4]:
# using @ module 
a = np.random.randint(1, 10, (2, 3, 4))  # 2 matrices of 3×4
b = np.random.randint(1, 10, (2, 4, 5))  # 2 matrices of 4×5

result = a @ b
print("Shape:", result.shape)


Shape: (2, 3, 5)


### matrix multiplication 

- Matrix multiplication is not element-wise multiplication.

- It’s a special way to combine two matrices where the columns of the first are matched with the rows of the second.

- Condition to multiply:
  - If
  - Matrix A → shape (m × n)
  - Matrix B → shape (n × p)
  - Then result → shape (m × p)

using ```np.matmul``` or ```@``` you can multiply two matrices 

In [5]:
# example 2D matrix multiplication 
import numpy as np

A = np.array([[1, 2],
              [3, 4]])     # Shape: (2, 2)

B = np.array([[5, 6],
              [7, 8]])     # Shape: (2, 2)

result = np.matmul(A, B)
# OR use A @ B
print(result)


[[19 22]
 [43 50]]


In [6]:
# example 3D matrix multiplication
A = np.random.randint(1, 5, (2, 3, 4))  # Two 3×4 matrices
B = np.random.randint(1, 5, (2, 4, 2))  # Two 4×2 matrices

C = np.matmul(A, B)  # or A @ B
print(C.shape)


(2, 3, 2)


### Multiplying a Matrix with a 1D Array

In [7]:
import numpy as np
import numpy.linalg
A = np.array([[1, 2],
              [3, 4]]) 
A @ np.ones(2)


array([3., 7.])

###  Matrix Inverse and QR Decomposition
- We use numpy.linalg for more advanced operations.

In [11]:
from numpy.linalg import inv, qr
rng = np.random.default_rng()
X = rng.standard_normal((5, 5))     # 5x5 random matrix
mat = X.T @ X                       # Multiply X transpose with X
inv(mat)      # Matrix inverse


array([[ 10.50343979, -39.31275773,   2.52002889,  18.39452468,
         -9.74954022],
       [-39.31275773, 153.42406606,  -7.67926789, -69.8562294 ,
         36.82373852],
       [  2.52002889,  -7.67926789,   1.56758481,   4.386645  ,
         -2.35748974],
       [ 18.39452468, -69.8562294 ,   4.386645  ,  32.71007719,
        -17.34483425],
       [ -9.74954022,  36.82373852,  -2.35748974, -17.34483425,
          9.47848786]])

In [12]:
# Check if the inverse is correct:
mat @ inv(mat)   # should give you the identity matrix


array([[ 1.00000000e+00, -1.55524121e-14,  1.23781844e-15,
        -3.87612693e-15, -3.22117702e-15],
       [-2.41363758e-15,  1.00000000e+00, -1.03786904e-15,
         1.05293843e-14,  5.71631702e-15],
       [-1.65231011e-14,  7.49637753e-15,  1.00000000e+00,
        -3.73900563e-14,  3.57405441e-15],
       [ 9.31224547e-15,  4.54962597e-14,  2.17668023e-15,
         1.00000000e+00,  1.09671447e-14],
       [-3.16069796e-15,  2.06982176e-14, -1.45468205e-15,
         4.57123264e-15,  1.00000000e+00]])

### Determinant and inverse in numpy 

- These are essential concepts in linear algebra, especially when solving systems of equations or checking if a matrix is invertible.


#### Determinant ?

- determinant is a single number calculated from square matrix 

- Why is it important?

    - It tells us whether a matrix is invertible.

    - If det(A) ≠ 0 → matrix is invertible ✅

    - If det(A) = 0 → matrix is singular ❌ (no inverse) 

In [ ]:
# example of 2x2 matrix 
import numpy as np

A = np.array([[2, 3],
              [1, 4]])

det_A = np.linalg.det(A)
print("Determinant:", det_A)


 # What is the Inverse of a Matrix?

- The inverse of a matrix A is another matrix A⁻¹ 
- Where I is the identity matrix.

- In simpler words: it's like division in matrix world.
   A⁻¹ “undoes” what A does.

In [7]:
A = np.array([[2, 3],
              [1, 4]])

inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)


Inverse of A:
 [[ 0.8 -0.6]
 [-0.2  0.4]]


example of 3x3 matrix example 

In [8]:
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

inv_A = np.linalg.inv(A)
print("Inverse:\n", inv_A)


Inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


### some common linear algebra fucntion 

| Function                | Description                  |
| ----------------------- | ---------------------------- |
| `dot(a, b)` or `a @ b`  | Matrix multiplication        |
| `inv(a)`                | Inverse of a square matrix   |
| `transpose(a)` or `a.T` | Transpose of a matrix        |
| `det(a)`                | Determinant of a matrix      |
| `eig(a)`                | Eigenvalues and eigenvectors |
| `svd(a)`                | Singular value decomposition |
| `qr(a)`                 | QR decomposition             |
| `solve(a, b)`           | Solve linear system Ax = b   |
| `norm(a)`               | Vector or matrix norm        |
