1 . ```permutation()``` 

- Returns a new randomly permuted version of a sequence or range
- In this The original array remains unchanged

In [17]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,0])
permuted = np.random.permutation(arr)
print(permuted)
print(permuted)

[1 3 9 6 7 4 5 0 8 2]
[1 3 9 6 7 4 5 0 8 2]


2. ```shuffle()```

-  Randomly shuffles the original array in place
-  modifies the original array directly  

In [21]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)


[1 3 2 4 5]


3. ```uniform()```
   
- Generates random numbers uniformly between a specified low and high.
- Every number in the range has equal chance of appearing.



In [43]:
# From [1.0, 5.0), size=5
samples = np.random.uniform(1.0, 5.0, size=5)
print(samples)


[1.97306061 3.48340794 3.7350239  1.47457441 3.944616  ]


4. ```integer()```

- generate a random integer in a give range [low , high]

In [33]:
rng = np.random.default_rng()
rand_ints = rng.integers(10, 20, size=5)
print(rand_ints)
#  Numbers will be between 10 (inclusive) and 20 (exclusive).

[18 12 18 16 11]


5. ```standard_normal()```

- use: Samples from a normal distribution with:

   - mean = 0

   - standard deviation = 1

In [49]:
data = np.random.standard_normal(size=(2, 3))
print(data)


[[-1.55277255 -0.00505552 -0.7528694 ]
 [ 0.66914956 -0.43842817 -0.58376148]]


6. ```binomial()```
   
- samples from a binomial distribution(like coin toss)

In [52]:
# 10 trials, probability of success = 0.5, size = 5 samples
samples = np.random.binomial(n=10, p=0.5, size=5)
print(samples)


[2 7 4 6 6]


7. ```normal()```

- draw samples for a gaussian(normal) distribution 

In [ ]:
# Mean = 5, Std dev = 2, size = 5
samples = np.random.normal(loc=5, scale=2, size=5)
print(samples)
# you can customize mean and standard deviation

[6.08855602 8.31437473 5.69418749 0.08039137 7.05789213]


8. ```beta()```

-  Samples from a Beta distribution (values between 0 and 1, used in probability models).

In [ ]:
samples = np.random.beta(a=2.0, b=5.0, size=5)
print(samples)
# Used in Bayesian statistics and modeling.

[0.17930371 0.66423091 0.05992835 0.31775923 0.07586219]


9. ```chisquare()```

- draw samples on chisquare division

In [56]:
samples = np.random.chisquare(df=2, size=5)
print(samples)
# Useful in hypothesis testing and statistics

[1.42233271 0.05705022 6.96595147 2.66312916 3.34446091]


9. ```gamma()```

- draw a samples from a gamma distribution 

In [58]:
samples = np.random.gamma(shape=2.0, scale=2.0, size=5)
print(samples)
# Used in survival analysis and queuing models.

[5.06596603 4.88838348 2.82310162 2.70102069 3.42506482]


10. ```uniform()```

- you mention uniform twice - both are same 
- it draw a samples from a uniform distribution between [0.0 , 1.0] if no range is specified 

In [59]:
samples = np.random.uniform(size=5)
print(samples)


[0.76161175 0.18736801 0.95341128 0.3479759  0.75561306]


11 . ```np.random.rand()```

- generates random number from a uniform distributions over[(0,1)]

- syntax:
  -  ``` np.random.rand(d0,d1.....dn)```

In [ ]:
import numpy as np 
print(np.random.rand(5)) # 1D array with random 5 float between 0 to 1

[0.40720086 0.29973971 0.84644511 0.68371472 0.57981235]


In [13]:
import numpy as np
print(np.random.rand(2,6)) # 2D (2x3) array with random float value 

[[0.8532178  0.96531609 0.51816567 0.80644458 0.71869747 0.57352941]
 [0.53031151 0.46124243 0.47961519 0.72408586 0.18349746 0.94515915]]


12 . ```np.random.randn() ```

- generates random number from standard normal distributions (mean=0 ,std = 1)

- syntax :
  - ``` np.random.randn(d0,d1,.....dn)``` 

In [16]:
print(np.random.randn(5)) #  1D array of 5 values from normal distribution

# 2D array (2x2)
print(np.random.randn(2, 2))

[ 0.28303138 -0.57828045 -0.31218043 -1.07285053  0.84005849]
[[0.53501886 1.45660246]
 [0.74518873 0.56362029]]


difference between rand() and randn()

- rand() is uniform distribution 
  - randn() is standard normal distribution 

- rand() range is [o,1]
  - randn() range is [-infinte, +infinite] 

13. ```np.random.randint()``` 

- it generates random integer between the given range

- syntax:
  
  - ```np.random.randint(low, high=None, size=None)```
  - low = strt
  - high = end
  - size = shape of the output array 
  

In [23]:
# single integer between 10 to 20
print(np.random.randint(10 , 20))
# 1D array of 20 integer between 0 to 100
print(np.random.randint(0 , 100, size = 20))
# 2D array (2x3) of random integer 
print(np.random.randint(1,10,size=(2,3)))

15
[51  7 49 67 17 78 73 92 18 19 49  8  6 84 56 26  7 76 82 13]
[[8 9 5]
 [1 5 3]]


14 . ```np.random.seed()```

- sets the seed for the random number generator to make result reproducible 

In [ ]:
np.random.seed(42)
print(np.random.rand(3))  # Same result every time you run it

np.random.seed(42)
print(np.random.rand(3))  # Same again due to same seed

np.random.seed(45)
print(np.random.rand(3)) # different because different seed 


[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]
[0.98901151 0.54954473 0.2814473 ]


Very useful when you want your random results to be consistent for testing or demonstration.



15. ```np.random.choice()```

- randomly select an element from 1 D array 
- syntax:
  - ```np.random.choice(array, size=None, replace=True, p=None)```
  

In [26]:
arr = np.array[1,23,4,0,9,90]
print(arr)

TypeError: 'builtin_function_or_method' object is not subscriptable