# Pseudorandom Number Generation

- Pseudorandom numbers are not truly random. Instead, they are deterministically generated using mathematical formulas or algorithms.

- The sequence appears random, but it is predictable if you know the starting point, which is called the seed.

## Why Use NumPy for Random Numbers?

- NumPy provides a powerful random module that allows you to:

- Generate random numbers from uniform, normal, and other distributions.

- Create random integers, floating point numbers, shuffled arrays, and more.

- Control reproducibility with a seed value.



In [1]:
# example 
import numpy as np 
sample = np.random.standard_normal(size=(4,4))
print(sample)

[[-0.84607316  0.12181762  1.3496182   1.66828831]
 [ 1.12114385 -0.90922624 -0.20067742  0.19840471]
 [-1.02061192 -2.18095391  0.08877509  0.65908125]
 [-0.28743447  0.15494369 -1.25511876 -0.2211089 ]]


In NumPy, when we generate "random" numbers, they are not truly random.
They are pseudorandom, which means:

- They look random, but are actually generated using a formula that follows a pattern.
  So, they are deterministic — if you start with the same setup, you get the same result.

- numpy has some built in systems that generate which helps you to generate random numbers 
    - by defalult ```np.random.standard_normal(size = (4 ,4))```  , 
  you are using numpy default random number generator 



But sometimes, especially in research or testing, you may want to:

 - Control how random numbers are generated.

 - Make sure you can reproduce the same results every time.



solution is to create your generator 

In [ ]:
# you can create your generator like this 
rng = np.random.default_rng(seed=12345)

# rng is your personal generator 
# seed= 1234 is ensures that every time you run the code 
# It's like planting the same seed in a garden—you know what will grow.


now use rng to generate random numbers 

In [4]:
data = rng.standard_normal((2, 3))
print(data)


[[-1.3677927   0.6488928   0.36105811]
 [-1.95286306  2.34740965  0.96849691]]


### Advantage of Using Your Own Generator
  - rng is independent from the global np.random, so other code won't affect it.

  - You can manage randomness better, especially in large projects or simulations.

example 

In [5]:
import numpy as np

rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
print(data)


[[-1.42382504  1.26372846 -0.87066174]
 [-0.25917323 -0.07534331 -0.74088465]]


# numpy random number generator method 

1 . ```permutation()``` 

- Returns a new randomly permuted version of a sequence or range
- In this The original array remains unchanged

In [17]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,0])
permuted = np.random.permutation(arr)
print(permuted)
print(permuted)

[1 3 9 6 7 4 5 0 8 2]
[1 3 9 6 7 4 5 0 8 2]


2. ```shuffle()```

-  Randomly shuffles the original array in place
-  modifies the original array directly  

In [21]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)


[1 3 2 4 5]


3. ```uniform()```
   
- Generates random numbers uniformly between a specified low and high.
- Every number in the range has equal chance of appearing.



In [43]:
# From [1.0, 5.0), size=5
samples = np.random.uniform(1.0, 5.0, size=5)
print(samples)


[1.97306061 3.48340794 3.7350239  1.47457441 3.944616  ]


4. ```integer()```

- generate a random integer in a give range [low , high]

In [33]:
rng = np.random.default_rng()
rand_ints = rng.integers(10, 20, size=5)
print(rand_ints)
#  Numbers will be between 10 (inclusive) and 20 (exclusive).

[18 12 18 16 11]


5. ```standard_normal()```

- use: Samples from a normal distribution with:

   - mean = 0

   - standard deviation = 1

In [49]:
data = np.random.standard_normal(size=(2, 3))
print(data)


[[-1.55277255 -0.00505552 -0.7528694 ]
 [ 0.66914956 -0.43842817 -0.58376148]]


6. ```binomial()```
   
- samples from a binomial distribution(like coin toss)

In [52]:
# 10 trials, probability of success = 0.5, size = 5 samples
samples = np.random.binomial(n=10, p=0.5, size=5)
print(samples)


[2 7 4 6 6]


7. ```normal()```

- draw samples for a gaussian(normal) distribution 

In [ ]:
# Mean = 5, Std dev = 2, size = 5
samples = np.random.normal(loc=5, scale=2, size=5)
print(samples)
# you can customize mean and standard deviation

[6.08855602 8.31437473 5.69418749 0.08039137 7.05789213]


8. ```beta()```

-  Samples from a Beta distribution (values between 0 and 1, used in probability models).

In [ ]:
samples = np.random.beta(a=2.0, b=5.0, size=5)
print(samples)
# Used in Bayesian statistics and modeling.

[0.17930371 0.66423091 0.05992835 0.31775923 0.07586219]


9. ```chisquare()```

- draw samples on chisquare division

In [56]:
samples = np.random.chisquare(df=2, size=5)
print(samples)
# Useful in hypothesis testing and statistics

[1.42233271 0.05705022 6.96595147 2.66312916 3.34446091]


9. ```gamma()```

- draw a samples from a gamma distribution 

In [58]:
samples = np.random.gamma(shape=2.0, scale=2.0, size=5)
print(samples)
# Used in survival analysis and queuing models.

[5.06596603 4.88838348 2.82310162 2.70102069 3.42506482]


10. ```uniform()```

- you mention uniform twice - both are same 
- it draw a samples from a uniform distribution between [0.0 , 1.0] if no range is specified 

In [59]:
samples = np.random.uniform(size=5)
print(samples)


[0.76161175 0.18736801 0.95341128 0.3479759  0.75561306]
