# Pseudorandom Number Generation

- Pseudorandom numbers are not truly random. Instead, they are deterministically generated using mathematical formulas or algorithms.

- The sequence appears random, but it is predictable if you know the starting point, which is called the seed.

## Why Use NumPy for Random Numbers?

- NumPy provides a powerful random module that allows you to:

- Generate random numbers from uniform, normal, and other distributions.

- Create random integers, floating point numbers, shuffled arrays, and more.

- Control reproducibility with a seed value.



In [1]:
# example 
import numpy as np 
sample = np.random.standard_normal(size=(4,4))
print(sample)

[[-0.84607316  0.12181762  1.3496182   1.66828831]
 [ 1.12114385 -0.90922624 -0.20067742  0.19840471]
 [-1.02061192 -2.18095391  0.08877509  0.65908125]
 [-0.28743447  0.15494369 -1.25511876 -0.2211089 ]]


In NumPy, when we generate "random" numbers, they are not truly random.
They are pseudorandom, which means:

- They look random, but are actually generated using a formula that follows a pattern.
  So, they are deterministic — if you start with the same setup, you get the same result.

- numpy has some built in systems that generate which helps you to generate random numbers 
    - by defalult ```np.random.standard_normal(size = (4 ,4))```  , 
  you are using numpy default random number generator 



But sometimes, especially in research or testing, you may want to:

 - Control how random numbers are generated.

 - Make sure you can reproduce the same results every time.



solution is to create your generator 

In [ ]:
# you can create your generator like this 
rng = np.random.default_rng(seed=12345)

# rng is your personal generator 
# seed= 1234 is ensures that every time you run the code 
