## universal function

- a function that perform element-wise operation on data in ndarray 

- A Universal Function (ufunc) is a vectorized wrapper for a function that operates element-wise on ndarray objects.

- They're fast, efficient, and broadcast-compatible
   
   - Broadcast-compatible = Broadcast-compatible means that two arrays of different shapes can still be used together in element-wise operations by stretching the smaller array automatically without copying data. This is called broadcasting.  

### Key Characteristics of ufuncs:

- Operate element-wise on arrays

- Broadcasting supported

- Type casting is handled

- Can take multiple input/output arrays

- Much faster than Python loops

##  categories of universal function 



### 1. Arthimatical functions 

- these perform basic mathematical operations
- like :
  - addition
  - substraction
  - multiplication
  - divide 
  - power 
  - mod  

1. ```np.add(x,y)```

- add corresponding element of two different arrays 

In [3]:
# in 1d array
import numpy as np
result = np.add([1, 2], [3, 4])  # 1+3 , 2+4
print(result) 
# in 2D array 

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.add(a, b)
print(result)



[4 6]
[[ 6  8]
 [10 12]]


2. ```np.subtract(x,y)```


In [ ]:
# in 1D array 
result = np.subtract([3,4],[1,2])
print(result)
# in 2D array
a = np.array([[10, 20], [30, 40]])
b = np.array([[1, 2], [3, 4]])

result = np.subtract(a, b)
print(result)



[2 2]
[[ 9 18]
 [27 36]]


3. ```np.muliply(x,y)```

In [ ]:
# in 2D array
a = np.array([[10, 20], [30, 40]])
b = np.array([[1, 2], [3, 4]])

result = np.multiply(a, b)
print(result)


[[ 10  40]
 [ 90 160]]


4. ```np.divide(x,y)```



In [ ]:
a = np.array([[10, 20], [30, 40]])
b = np.array([[1, 2], [3, 4]])

result = np.divide(a, b)
print(result)


5. ```np.power(x,y)``` 

- exponentiation(x raised to the power y)
- Raises each element in x to the power of corresponding element in y (or scalar).

In [ ]:
result = np.power([2, 3], 2)
print(result)  



[4 9]


In [9]:
a = np.array([[2, 3], [4, 5]])
result = np.power(a, 2)
print(result)


[[ 4  9]
 [16 25]]


In [10]:
# 3D array
a = np.array([[[2, 3], [4, 5]], [[1, 2], [3, 4]]])
b = np.array([[[2, 2], [2, 2]], [[3, 3], [3, 3]]])

result = np.power(a, b)
print(result)


[[[ 4  9]
  [16 25]]

 [[ 1  8]
  [27 64]]]


6. ```np.mod(x,y)```

- modulus 
- Returns the remainder of division of x by y

In [ ]:
# 2D array
a = np.array([[10, 20], [30, 40]])
b = np.array([[3, 4], [5, 6]])

result = np.mod(a, b)
print(result)


In [ ]:
# 3D array
a = np.array([[[10, 20], [30, 40]], [[15, 25], [35, 45]]])
b = np.array([[[2, 3], [4, 5]], [[6, 7], [8, 9]]])

result = np.mod(a, b)
print(result)


### 2. comparison function

1. ```np.equal(x,y)``` 

- x==y
- compare the element of two different array whether it is equal or not

In [11]:
import numpy as np

a = np.array([1, 2])
b = np.array([1, 3])

result = np.equal(a, b)
print(result)


[ True False]


2. ```np.not_equal(x,y)```

- x!=y
-  Checks whether elements of x and y are not equal.



In [12]:
a = np.array([1, 2])
b = np.array([1, 3])

result = np.not_equal(a, b)
print(result)

[False  True]


3. ```np.greater(x,y)``` 


- x>y
- Checks where elements in x are greater than y.



In [ ]:
a = np.array([3, 2])
b = np.array([2, 2])

result = np.greater(a, b)
print(result)


4. ```np.greater_equal(x,y)```

- x>=y
- check the element in x is greater than or equal to y

In [13]:
a = np.array([3, 2, 1])
b = np.array([2, 2, 3])

result = np.greater_equal(a, b)
print(result)


[ True  True False]


5. ```np.less(x,y)```

- x<y
- Checks where elements in x are less than y.

In [14]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

result = np.less(a, b)
print(result)


[ True False False]


6. ```np.less_equal(x,y)```

- Checks where elements in x are less than or equal to y.

In [15]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

result = np.less_equal(a, b)
print(result)


[ True  True False]


###