## universal function

- a function that perform element-wise operation on data in ndarray 

- A Universal Function (ufunc) is a vectorized wrapper for a function that operates element-wise on ndarray objects.

- They're fast, efficient, and broadcast-compatible
   
   - Broadcast-compatible = Broadcast-compatible means that two arrays of different shapes can still be used together in element-wise operations by stretching the smaller array automatically without copying data. This is called broadcasting.  

### Key Characteristics of ufuncs:

- Operate element-wise on arrays

- Broadcasting supported

- Type casting is handled

- Can take multiple input/output arrays

- Much faster than Python loops

##  categories of universal function 



### 1. Arthimatical functions 

- these perform basic mathematical operations
- like :
  - addition
  - substraction
  - multiplication
  - divide 
  - power 
  - mod  

1. ```np.add(x,y)```

- add corresponding element of two different arrays 

In [3]:
# in 1d array
import numpy as np
result = np.add([1, 2], [3, 4])  # 1+3 , 2+4
print(result) 
# in 2D array 

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.add(a, b)
print(result)



[4 6]
[[ 6  8]
 [10 12]]


2. ```np.subtract(x,y)```


In [ ]:
# in 1D array 
result = np.subtract([3,4],[1,2])
print(result)
# in 2D array
a = np.array([[10, 20], [30, 40]])
b = np.array([[1, 2], [3, 4]])

result = np.subtract(a, b)
print(result)



[2 2]
[[ 9 18]
 [27 36]]


3. ```np.muliply(x,y)```

In [ ]:
# in 2D array
a = np.array([[10, 20], [30, 40]])
b = np.array([[1, 2], [3, 4]])

result = np.multiply(a, b)
print(result)


[[ 10  40]
 [ 90 160]]


4. ```np.divide(x,y)```



In [ ]:
a = np.array([[10, 20], [30, 40]])
b = np.array([[1, 2], [3, 4]])

result = np.divide(a, b)
print(result)


5. ```np.power(x,y)``` 

- exponentiation(x raised to the power y)
- Raises each element in x to the power of corresponding element in y (or scalar).

In [ ]:
result = np.power([2, 3], 2)
print(result)  



[4 9]


In [9]:
a = np.array([[2, 3], [4, 5]])
result = np.power(a, 2)
print(result)


[[ 4  9]
 [16 25]]


In [10]:
# 3D array
a = np.array([[[2, 3], [4, 5]], [[1, 2], [3, 4]]])
b = np.array([[[2, 2], [2, 2]], [[3, 3], [3, 3]]])

result = np.power(a, b)
print(result)


[[[ 4  9]
  [16 25]]

 [[ 1  8]
  [27 64]]]


6. ```np.mod(x,y)```

- modulus 
- Returns the remainder of division of x by y

In [ ]:
# 2D array
a = np.array([[10, 20], [30, 40]])
b = np.array([[3, 4], [5, 6]])

result = np.mod(a, b)
print(result)


In [ ]:
# 3D array
a = np.array([[[10, 20], [30, 40]], [[15, 25], [35, 45]]])
b = np.array([[[2, 3], [4, 5]], [[6, 7], [8, 9]]])

result = np.mod(a, b)
print(result)


### 2. comparison function

1. ```np.equal(x,y)``` 

- x==y
- compare the element of two different array whether it is equal or not

In [11]:
import numpy as np

a = np.array([1, 2])
b = np.array([1, 3])

result = np.equal(a, b)
print(result)


[ True False]


2. ```np.not_equal(x,y)```

- x!=y
-  Checks whether elements of x and y are not equal.



In [12]:
a = np.array([1, 2])
b = np.array([1, 3])

result = np.not_equal(a, b)
print(result)

[False  True]


3. ```np.greater(x,y)``` 


- x>y
- Checks where elements in x are greater than y.



In [ ]:
a = np.array([3, 2])
b = np.array([2, 2])

result = np.greater(a, b)
print(result)


4. ```np.greater_equal(x,y)```

- x>=y
- check the element in x is greater than or equal to y

In [13]:
a = np.array([3, 2, 1])
b = np.array([2, 2, 3])

result = np.greater_equal(a, b)
print(result)


[ True  True False]


5. ```np.less(x,y)```

- x<y
- Checks where elements in x are less than y.

In [14]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

result = np.less(a, b)
print(result)


[ True False False]


6. ```np.less_equal(x,y)```

- Checks where elements in x are less than or equal to y.

In [15]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

result = np.less_equal(a, b)
print(result)


[ True  True False]


### 3. trigonometry function 


1. ```np.sin(array)``` 

- it is basically a (-Sinx)
-  Computes the sine of each element in x (in radians).

In [16]:
import numpy as np

x = np.array([0, np.pi/2, np.pi]) # o is just 0 degree and np.pi/2 is also 90 degree in radian or np.pi is 180 degree but in radian 
result = np.sin(x)
print(result)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


2. ```np.cos(array)```

- it is basically a (-cosine)
- Computes the cosine of each element in x (in radians).





In [17]:
x = np.array([0, np.pi/2, np.pi])
result = np.cos(x)
print(result)


[ 1.000000e+00  6.123234e-17 -1.000000e+00]


3. ```np.tangent(array)

- it is basically a (-tangent )

In [18]:
x = np.array([0, np.pi/4, np.pi/2])
result = np.tan(x)
print(result)


[0.00000000e+00 1.00000000e+00 1.63312394e+16]


4. ```arcsin(array)```

- it is reverse of sin
- it compute arcsin(inverse of sin ) of x
- Input Range: x ∈ [-1, 1]
- Output Range: in radians from -π/2 to π/2

In [19]:
x = np.array([0, 0.5, 1])
result = np.arcsin(x)
print(result)


[0.         0.52359878 1.57079633]


5. ```np.arccos(array) ```

- it is a inverse of cosine
-  Computes the arccosine (inverse cosine) of x.
- Input Range: x ∈ [-1, 1]
- Output Range: in radians from 0 to π

In [20]:
x = np.array([1, 0.5, 0])
result = np.arccos(x)
print(result)


[0.         1.04719755 1.57079633]


6. ```np.arctan(array)```

- it is basically inverse of tangent 
- Computes the arctangent (inverse tangent) of x.
- Input Range: all real numbers
- Output Range: in radians from -π/2 to π/2

In [21]:
x = np.array([0, 1, np.sqrt(3)])
result = np.arctan(x)
print(result)


[0.         0.78539816 1.04719755]


here in trigonometry function input is usually in radian you can use ```np.deg2rad()``` or ```np.rad2deg()``` to convert 

```np.deg2rad(degree) ```

- it is used to convert degree to radians 
- When your angle is in degrees but you want to use it in a trigonometric function (which expects radians).

In [22]:
import numpy as np

degrees = np.array([0, 90, 180])
radians = np.deg2rad(degrees)

print(radians)


[0.         1.57079633 3.14159265]


```np.rad2deg(radian)```

- it is used to convert radian to degree 
- When the result of a trigonometric function is in radians, and you want to convert it to degrees.

In [23]:
radians = np.array([0, np.pi/2, np.pi])
degrees = np.rad2deg(radians)

print(degrees)


[  0.  90. 180.]


### 4. exponential fucntion

1. ```np.exp(x) ``` - exponential function

- This calculates e to the power x (e ≈ 2.718).

- It's like doing: e^x

In [25]:
import numpy as np

x = np.array([1, 2])
result = np.exp(x)
print(result) # e^1,e^2


[2.71828183 7.3890561 ]


2. ```expm1(x) - e^x-1

- it calculate e^x-1 ,but more accurate for the small x 
- Good for avoiding floating-point errors when x is very small. 

In [ ]:
x = np.array([0, 1])
result = np.expm1(x)
print(result) # e^0-1  e^1-1


[0.         1.71828183]


3. ```np.log(x)``` - natural log(ln)

- This gives the natural logarithm of x, which is log base e.

- It answers: “What power should e be raised to, to get x?”

In [27]:
x = np.array([1, np.e])
result = np.log(x)
print(result)


[0. 1.]


4. ```np.log2(x)``` - log base 2 

- This calculates logarithm of x with base 2.

- Used in computer science (binary systems).



In [28]:
x = np.array([1, 2, 4, 8])
result = np.log2(x)
print(result)


[0. 1. 2. 3.]


5. ```log10(x)``` log base 10

- This calculates logarithm of x with base 10.

- Used in scientific calculations (like measuring sound, earthquakes, etc.).



In [29]:
x = np.array([1, 10, 100, 1000])
result = np.log10(x)
print(result)


[0. 1. 2. 3.]


### 5. Aggregation function

1. ```np.sum()```

- sum of all element 

In [30]:
a = np.array([1, 2, 3])
np.sum(a)


np.int64(6)

2. ```np.prod()``` 

- product of all element 

In [31]:
a = np.array([1, 2, 3, 4])
np.prod(a)


np.int64(24)

3. ```np.mean(array)``` 

- avearage (mean)
- add the element and divide by its count 

In [32]:
a = np.array([1, 2, 3, 4])
np.mean(a)


np.float64(2.5)

4. ```np.std(array)```

- standard deviation
- Tells how spread out the values are from the mean.

In [33]:
a = np.array([1, 2, 3])
np.std(a)


np.float64(0.816496580927726)

5. ```np.var()```

- variance 
- It's the square of standard deviation.
- Shows how much the values vary from the mean.

In [34]:
a = np.array([1, 2, 3])
np.var(a)


np.float64(0.6666666666666666)

6. ```np.min()/np.max() ```

smallest and largest value 

In [36]:
a = np.array([4, 2, 9, 1])
x= np.min(a)     
y= np.max(a)     
print(x)
print(y)


1
9


7. ```np.argmin()/np.argmax()```

- index of minimum and maximum 
- np.argmin() → Position of the smallest number
- np.argmax() → Position of the biggest number

In [37]:
a = np.array([4, 2, 9, 1])
np.argmin(a)   # Output: 3 (index of 1)
np.argmax(a)   # Output: 2 (index of 9)


np.int64(2)

### 6. rounding and special function

1.``` np.around(x)``` 

- round to the nearest value 
- It rounds the number to the nearest whole number or to given decimal places.



In [ ]:
import numpy as np
x = np.array([1.4, 2.6, 3.5])
np.around(x)


2. ```np.floor(x)```

- round down 
- alaways round down to the nearest lower whole number 

In [ ]:
x = np.array([1.9, 2.3, -1.7])
np.floor(x)


3. ```np.ceil(x)```

- Always rounds up to the nearest higher whole number.



In [38]:
x = np.array([1.1, 2.7, -1.2])
np.ceil(x)


array([ 2.,  3., -1.])

4. ```np.trunc(x)```

- it removes decimal and Cuts off the decimal part (doesn’t round, just removes it).

In [39]:
x = np.array([1.9, -2.7])
np.trunc(x)


array([ 1., -2.])

5. ```np.sqrt(x)```

- square root 
- Returns the square root of each element.



In [40]:
x = np.array([4, 9, 16])
np.sqrt(x)


array([2., 3., 4.])

6. ```np.abs(x)```

- absolute value 
- Returns the positive version of each number (removes negative sign).



In [41]:
x = np.array([-1, -2.5, 3])
np.abs(x)


array([1. , 2.5, 3. ])

### 7. Bitwise function

- Bitwise operations work on bits (0s and 1s) of integers.
- Example:

- Binary of 6 → 110

- Binary of 3 → 011

1. ```np.bitwise_and(x,y) ```

- bitwise and 
- Returns 1 only when both bits are 1, otherwise 0.

In [42]:
x = np.array([6])    # binary: 110
y = np.array([3])    # binary: 011
np.bitwise_and(x, y)


array([2])

2. ```np.bitwise_or(x,y)```

- Returns 1 if either bit is 1.



In [43]:
np.bitwise_or(6, 3)


np.int64(7)

3. ```np.bitwise_xor(x,y)```

- Returns 1 if bits are different, 0 if same.

In [44]:
np.bitwise_xor(6, 3)


np.int64(5)

4. ```np.invert(x)```

- bitwise not 
- Flips all bits (0 → 1 and 1 → 0). Works on signed numbers using 2’s complement.



In [ ]:
np.invert(np.array([6]))


5. ```np.left_shift(x,n)``` - shift left 

- Shifts bits to the left n times. Each shift = ×2.



In [46]:
np.left_shift(5, 1)


np.int64(10)

6. ```np.right_shift(x,n) ``` - right shift 

- Shifts bits to the right n times. Each shift = ÷2.

In [45]:
np.right_shift(10, 1)


np.int64(5)

### 8. logical functions 

- Logical operations check the truth value of conditions:

   - True means the condition is satisfied.

   - False means it's not.

Logical functions are mostly used for arrays with boolean values or conditions.



1. ```np.logical_and(x,y) ``` - logical and 

- return true if both the x and y are true else its return false 

In [47]:
import numpy as np
x = np.array([True, False, True])
y = np.array([True, True, False])

np.logical_and(x, y)


array([ True, False, False])

2. ```logical_or(x,y)``` - logical or 

- return true if either of x and y is true else return false  

In [ ]:
np.logical_or(x, y)


3. ```np.logical_xor(x,y) ``` - logical xor(exclusive or)

- return true if eighter of x and y is true , not both 

In [48]:
np.logical_xor(x, y)


array([False,  True,  True])

*** remember ***

 NumPy treats:

0 as False

Any non-zero number as True

### 9. where function
- Useful for conditional element-wise selection.

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 25, 3, 35])

# Choose from a if condition is True else from b
np.where(a > b, a, b)



array([10, 25, 30, 40])

### some universal fucntion can return multiple output 

<mark> - example : </mark>

### 1. np.modf():

- The function np.modf() splits each number in an array into two parts:

  - 1. Fractional part (after the decimal)

  - 2. Whole (integral) part (before the decimal)

It returns two arrays:

- First: Fractional part

- Second: Whole (integer) part

In [52]:
import numpy as np

rng = np.random.default_rng()   # create a Generator instance
arr = rng.standard_normal(7) * 5 # 7 random number multiply by each element by 5 
print(arr)
remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)



[-8.15632039  7.25729173  6.77145917  1.43763854  2.27055815 -9.24536071
  1.16135973]
[-0.15632039  0.25729173  0.77145917  0.43763854  0.27055815 -0.24536071
  0.16135973]
[-8.  7.  6.  1.  2. -9.  1.]


# out statement 

- To store the result of a ufunc in an existing array, instead of creating a new array. This is done using the out= argument.
- You can pass an existing array using out= in NumPy ufuncs to store the result directly, instead of creating a new array every time.

In [60]:
print(arr)
out = np.zeros_like(arr)  # creates a new array called out np.zeros_like(arr) means: ➝ Make an array of 0s that is the same shape and type as arr

print(out)
# np.add(arr,1)  #arr + 1 But it creates a new array in memory

# add 1 in arr but store result in out
np.add(arr, 1, out=out)
print(out)
 



[-8.15632039  7.25729173  6.77145917  1.43763854  2.27055815 -9.24536071
  1.16135973]
[0. 0. 0. 0. 0. 0. 0.]
[-7.15632039  8.25729173  7.77145917  2.43763854  3.27055815 -8.24536071
  2.16135973]


Why Use out=?

Saves memory: Useful when working with big arrays

More control: You can reuse arrays

Better performance: Especially in large-scale numerical computing