## Broadcasting 

- Broadcasting is a powerful feature that allows NumPy to perform vectorized operations between arrays of different shapes, under specific rules.

- Broadcasting is the process by which NumPy automatically expands arrays of different shapes so that element-wise operations (like addition, multiplication, etc.) 

- performed without explicit looping or copying data.

In [2]:
# example 
import numpy as np 
a = np.array([1, 2, 3])
b = 2
print(a * b)  # Output: [2, 4, 6]


[2 4 6]


### general broadcasting rule 

- To perform element-wise operations on two arrays, NumPy compares their shapes starting from right to left.
   - 1. The dimensions are equal, or
   - 2. One of the dimensions is 1
  

### common broadcasting scenario 


###  1. scalar with array 

In [3]:
a = np.array([1, 2, 3])
print(a + 10)  # [11, 12, 13]


[11 12 13]


### 2. row vector with matrix 

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]



### 3. column vector with matrix 

In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[10],
              [20]])

print(A + B)


[[11 12 13]
 [24 25 26]]


### 4. numpy function that support broadcasting 

np.add, np.subtract, np.multiply, np.divide

np.maximum, np.minimum

np.dot and np.matmul use matrix rules (not element-wise)