## where fucntion 

- it is used for vectorized conditional logic—essential for writing fast, clean, and efficient code in machine learning and data analysis.



In [6]:
import numpy as np
# example conditional element selection
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)] # slow python method
print(result)
# fast numpy metod 
np.where(cond, xarr, yarr)



[np.float64(1.1), np.float64(2.2), np.float64(1.3), np.float64(1.4), np.float64(2.5)]


array([1.1, 2.2, 1.3, 1.4, 2.5])

advance example 

We want to replace:

  - All positive values with 2

  - All negative values with -2

In [10]:
import numpy as np

# Create a random number generator
rng = np.random.default_rng()

# Generate a 4x4 matrix with standard normal distribution
arr = rng.standard_normal((4, 4))

# Print the matrix
print("Original matrix:")
print(arr)

# Print a boolean matrix where True indicates values > 0
print("\nValues greater than 0:")
print(arr > 0)

# apply np.where
np.where(arr > 0, 2, -2)

# Replace only positive values with 2, leave others unchanged:
np.where(arr > 0,2,arr)



Original matrix:
[[-1.11877089  1.23927594 -0.01086932 -0.38197459]
 [-0.39030739  0.14745209  0.16512887 -1.70818942]
 [-0.13396554 -1.62997027  0.15935414 -0.63065157]
 [-0.4159565   0.54529204 -0.80105074  0.68260274]]

Values greater than 0:
[[False  True False False]
 [False  True  True False]
 [False False  True False]
 [False  True False  True]]


array([[-1.11877089,  2.        , -0.01086932, -0.38197459],
       [-0.39030739,  2.        ,  2.        , -1.70818942],
       [-0.13396554, -1.62997027,  2.        , -0.63065157],
       [-0.4159565 ,  2.        , -0.80105074,  2.        ]])

### This is extremely useful when you want to:

- Modify specific elements conditionally

- Retain the rest of the array unchanged

