### Numpy:

- NumPy (Numerical Python) is a fundamental Python library for performing scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently.

- support large number of data in the form of multidiimensional array and matrix . 

- used for mathematic calculation like linear algebra , fourier transform and random number capabilities etc .

- NumPy (Numerical Python) is a Python library used to perform fast mathematical operations on large datasets, especially using arrays and matrices.




# Why Use NumPy?

| Feature             | Reason                                                                 |
|---------------------|------------------------------------------------------------------------|
| ✅ **Performance**   | Much faster than Python lists, as it's implemented in C internally     |
| ✅ **Arrays**        | Supports multi-dimensional arrays efficiently                          |
| ✅ **Broadcasting**  | Automatically expands smaller arrays during operations                 |
| ✅ **Vectorization** | You can apply operations to entire arrays (like addition, multiplication) without loops |
| ✅ **Memory**        | Uses less memory than lists                                             |
| ✅ **Scientific Computing** | Includes functions for linear algebra, statistics, random sampling, and Fourier transforms |


## important terms in numpy

- ### 1. `np.array()`
  
  - used to create numpy array from python list or tuple 
    

In [3]:
import numpy as np
x = np.array([1,2,3])
print(type(x))


<class 'numpy.ndarray'>


- ### 2. ndarray (N- dimensional array)

  - this is the main object in numpy

  - it is a multidimensional container of homogenious elements(same data type)

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(type(arr))  # <class 'numpy.ndarray'>


<class 'numpy.ndarray'>


- ### 3. `.ndim` 

  - return the number of dimension(axes) of the array  

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(type(arr))  # <class 'numpy.ndarray'>
arr.ndim

<class 'numpy.ndarray'>


2

- ### 4. `.shape` 

  - it tells the stucture of the array(rows , column) 


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(type(arr))  # <class 'numpy.ndarray'>
arr.shape

<class 'numpy.ndarray'>


(2, 3)

- ### 4. `.size` 
 
  - it returns the total number of elements in the array

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(type(arr))  # <class 'numpy.ndarray'>
arr.size

<class 'numpy.ndarray'>


6

- ### 5. `.dtype`
 
  - it shows the datatype of the element present in the array 

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(type(arr))  # <class 'numpy.ndarray'>
arr.dtype

# In this case, int64 means that each element in the array is a 64-bit integer

<class 'numpy.ndarray'>


dtype('int64')

## Array can create a function :



- ### 1. np.zeros(shape) 

  - create an array of all zeroes 

In [ ]:
import numpy as np

X = np.zeros((3, 4))

print(X)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


- ### 2. np.ones(shape)

 - create an array of all ones 

In [15]:
import numpy as np

X = np.ones((3, 4))

print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


- ### 3. np.full(shape , values)
  
  - fill array with specific values  

In [16]:
import numpy as np

X = np.full((3, 4), 6)

print(X)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


- ### 4. np.arange(start , stop , step)
  
  - it is just like a range() but it is used for array 

In [19]:
import numpy as np

arr = np.arange(2, 12, 2)

print(arr)


[ 2  4  6  8 10]


- ### 5. np.linspace(start , stop , num)

  - return evenly spaced number between two points 

In [ ]:
import numpy as np

# Generate 5 evenly spaced numbers between 0 and 10 (inclusive)
arr = np.linspace(0, 10, 5)
x = np.linspace(2, 14,2)

print(arr)
print(x)
# How are the values calculated?
# step=  stop - step / num - 1 


[ 0.   2.5  5.   7.5 10. ]
[ 2. 14.]


- ### 6. np.random.rand()
  
  - create array with random float values(0 to 1)

In [22]:
import numpy as np

# Generate a single random float between 0 and 1
random_number = np.random.rand()
print(random_number)


0.24476478649179156


In [23]:
# Generate a 2x3 array of random floats between 0 and 1
random_array = np.random.rand(2, 3)
print(random_array)


[[0.80614465 0.52512265 0.62958289]
 [0.79807066 0.99071847 0.17610981]]


- ### 7. np.random.randint(low , high, size)
 
  - random integer  

In [36]:
import numpy as np

# Generate a single random integer between 0 (inclusive) and 10 (exclusive)
random_int = np.random.randint(0, 10)
print(random_int)


0


In [38]:
# Generate a 2x4 array of random integers between 5 (inclusive) and 15 (exclusive)
random_array = np.random.randint(5, 15, size=(2, 4))
print(random_array)


[[ 5  8  5  7]
 [12 13 13 11]]
