## Unique and other set logic 

- NumPy has some basic set operations for one-dimensional ndarrays. 

### Why Set Logic in NumPy?
- Set operations let you:

   - Identify unique values

   - Find common elements (intersection)

   - Detect differences between arrays

   - Combine arrays without duplicates (union)

   - Check membership across arrays

 All these are critical when cleaning or comparing datasets.

### some common set logic 

| **Function**       | **Purpose**                               | **Output Type**           |
| ------------------ | ----------------------------------------- | ------------------------- |
| `np.unique()`      | Get sorted unique values                  | 1D array                  |
| `np.intersect1d()` | Common elements (AND)                     | 1D array                  |
| `np.union1d()`     | All unique elements from both arrays (OR) | 1D array                  |
| `np.setdiff1d()`   | Elements in `a` not in `b` (A - B)        | 1D array                  |
| `np.setxor1d()`    | Symmetric difference (XOR)                | 1D array                  |
| `np.in1d()`        | Check if elements of `a` are in `b`       | 1D boolean array          |
| `np.isin()`        | Broadcasted version of `in1d`             | Boolean array (any shape) |


1. ```np.unique()```

- Returns sorted unique elements of an array.

In [6]:
import numpy as np
arr = np.array([3, 1, 2, 3, 4, 1, 2])
unique_vals = np.unique(arr)
print(unique_vals)
vals, counts = np.unique(arr, return_counts=True)
print(vals)
print(counts)



[1 2 3 4]
[1 2 3 4]
[2 2 2 1]


2. ```np.intersected1d()```

- Returns the sorted, unique values that are in both arrays (intersection).



In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
np.intersect1d(a, b)



array([3, 4])

3. ```np.union1d()```

- Returns the sorted, unique values that are in either array (union)

In [ ]:
np.union1d(a, b)



array([1, 2, 3, 4, 5, 6])

4. ```np.setdiff1d() ```

- Returns values in the first array that are not in the second (set difference).



In [9]:
np.setdiff1d(a, b)
# Output: [1 2]  # in `a` but not in `b`


array([1, 2])

5. ```np.setxor1d()```

- Returns elements that are in only one of the arrays (exclusive OR).



In [ ]:
np.setxor1d(a, b)
# Output: [1 2 5 6]


6. ``` np.in1d()```

- Tests whether each element of one array is in another. Returns a boolean array.



In [10]:
np.in1d([1, 2, 3], [2, 4])
# Output: [False  True False]


/tmp/ipykernel_6710/4237297067.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d([1, 2, 3], [2, 4])


array([False,  True, False])

7. ```np.isin()```

- Same as np.in1d, but supports broadcasting and works better with multidimensional arrays.



In [11]:
a = np.array([[1, 2], [3, 4]])
b = [1, 4]
np.isin(a, b)
# Output:
# [[ True False]
#  [False  True]]


array([[ True, False],
       [False,  True]])