## Why Use NumPy File I/O?

- In Machine Learning and data science projects, we often deal with large datasets or computed arrays (like features, model weights, etc.) that    we don’t want to compute again and again.

So, we need a way to:

  - ✅ Save arrays permanently on disk.

  - ✅ Load them again quickly when needed.

NumPy provides built-in tools to do this efficiently using binary formats (.npy, .npz).

### 2. np.save() – Save a Single Array to Disk
- ▶️ What it does:
   - Saves one NumPy array to a .npy file.

   - Uses a binary format (not human-readable) → very fast & efficient.



In [1]:
import numpy as np

arr = np.arange(10)           # Creates array: [0 1 2 3 4 5 6 7 8 9]
np.save("some_array", arr)    # Saves to 'some_array.npy'


What gets created?
A file named some_array.npy is created on your disk.

### 3. np.load() – Load a .npy File Back
- ▶️ What it does:
   - Loads the array back from the .npy file into a NumPy array.



In [ ]:
loaded_array = np.load("some_array.npy")
print(loaded_array)


[0 1 2 3 4 5 6 7 8 9]


### 4. np.savez() – Save Multiple Arrays Together
- ▶️ What it does:
   - Saves multiple arrays in a single file.

   - File format: .npz (a zipped archive of .npy files inside).

   - You can name each array using keywords.

In [4]:
arr = np.arange(10)
np.savez("archive.npz", a=arr, b=arr*2)


This creates a file called archive.npz, which contains:

an array named "a" with values [0 1 2 3 4 5 6 7 8 9]

an array named "b" with values [0 2 4 6 8 10 12 14 16 18]

### 5. Loading .npz File
- When you load a .npz file, you get an object like a dictionary. You can access arrays by the names you gave them (a, b etc.)

In [5]:
archive = np.load("archive.npz")
print(archive["a"])   # [0 1 2 3 4 5 6 7 8 9]
print(archive["b"])   # [0 2 4 6 8 10 12 14 16 18]


[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


### 6. np.savez_compressed() – Save with Compression
- ▶️ What it does:
  - Same as savez(), but compresses the file to save disk space.

  - Useful for large datasets

In [6]:
np.savez_compressed("compressed_archive.npz", a=arr, b=arr*2)


You get a compressed version of the .npz file. It works the same way when loading.

### summary table 
| Function                | Saves What?              | File Format | Load Method | Multiple Arrays | Compressed |
| ----------------------- | ------------------------ | ----------- | ----------- | --------------- | ---------- |
| `np.save()`             | Single array             | `.npy`      | `np.load()` | ❌               | ❌          |
| `np.savez()`            | Multiple arrays          | `.npz`      | `np.load()` | ✅               | ❌          |
| `np.savez_compressed()` | Multiple arrays (zipped) | `.npz`      | `np.load()` | ✅               | ✅          |
