### ndarray / multidimensional array :

- ndarray stands for N-dimensional array. It is the core data structure provided by NumPy for storing arrays of any number of dimensions.

- A NumPy ndarray is a homogeneous, multidimensional, contiguous memory array object that stores elements of the same data type.

- This is the primary object used in NumPy to store and operate on data efficiently.

### creating an ndarray 

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])                      # 1D array
arr2 = np.array([[1, 2], [3, 4]])               # 2D array
arr3 = np.array([[[1], [2]], [[3], [4]]])       # 3D array
print(arr1)

[1 2 3]


In [9]:
import numpy as np

a = np.array([[1, 2, 3], [1,2,3]])
print(type(a))  # <class 'numpy.ndarray'>

x =a * 10
print(x)


<class 'numpy.ndarray'>
[[10 20 30]
 [10 20 30]]


### Key properties of ndarray:

- 1.  `.ndim`
   
    - number of dimension of array(axes) 

- 2. `.shape`
   
   - tuple representing the size of each dimension 

- 3. `.size` 
   
   - totsl number of element 

- 4. `.dtype`

   - data type of the element 
   
- 5. `.itemsize`
  
   - size in bytes of each element 

- 6. `.nbytes`

   - total bytes consumes (size * itemsize)             

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)
print(arr.shape)    
print(arr.size)
print(arr.dtype)    
print(arr.itemsize)   
print(arr.nbytes)   


2
(2, 3)
6
int64
8
48


# Why Use `ndarray`?

- **Speed**: Much faster than Python lists due to internal optimizations (C-based).
- **Memory Efficiency**: Uses less memory than a list of lists.
- **Functionality**: Supports a wide range of mathematical, logical, and statistical operations.
- **Broadcasting**: Allows operations on arrays of different shapes.
- **Convenience**: Comes with lots of helpful methods and functions for reshaping, slicing, aggregation, and more.


 ### data type for ndarray

 - The data type or dtype is a special object containing the information (or metadata,
   data about data) the ndarray needs to interpret a chunk of memory as a particular
   type of data:

In [16]:
import numpy as np

arr1 = np.array([1,23,4] , dtype = np.float64)
arr2 = np.array([1,23,4] , dtype = np.int32)
arr3 = np.array([[1,2.2,3],[4,5,6]])
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)




float64
int32
float64


# Common NumPy Data Types

| Data Type   | Description                        | Example / Size         |
|-------------|------------------------------------|-------------------------|
| `int8`      | Integer (-128 to 127)              | 1 byte                 |
| `int16`     | Integer (-32k to 32k)              | 2 bytes                |
| `int32`     | Integer (standard 32-bit)          | 4 bytes                |
| `int64`     | Integer (large 64-bit)             | 8 bytes                |
| `float16`   | Half precision float               | 2 bytes                |
| `float32`   | Single precision float             | 4 bytes                |
| `float64`   | Double precision float             | 8 bytes                |
| `bool_`     | Boolean (True/False)               | 1 byte                 |
| `complex64` | Complex number (real + imag)       | 8 bytes                |
| `U10`       | Unicode string (max length 10)     | String data            |
| `object`    | Python object (slow, flexible)     | Mixed types            |


# NumPy Data Types: Summary Table

| Type              | Code(s)     | Description                                               |
|-------------------|-------------|-----------------------------------------------------------|
| `int8` / `uint8`   | `i1` / `u1` | Signed / Unsigned 8-bit (1 byte) integer                  |
| `int16` / `uint16` | `i2` / `u2` | Signed / Unsigned 16-bit (2 bytes) integer                |
| `int32` / `uint32` | `i4` / `u4` | Signed / Unsigned 32-bit (4 bytes) integer                |
| `int64` / `uint64` | `i8` / `u8` | Signed / Unsigned 64-bit (8 bytes) integer                |
| `float16`          | `f2`        | Half-precision floating-point (2 bytes)                   |
| `float32`          | `f4` or `f` | Single-precision float (standard C float)                 |
| `float64`          | `f8` or `d` | Double-precision float (Python float object)              |
| `float128`         | `f16` or `g`| Extended-precision float (platform dependent)             |
| `complex64`        | `c8`        | Complex number with two 32-bit floats (real + imag)       |
| `complex128`       | `c16`       | Complex nu


- You can explicitly convert and cast one data type to other data type using ndarray `astype` method 

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4],[1,2,3,4]])
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

# in this example you convert this into int to float 

int64
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]
float64


In [ ]:
import numpy as np
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr.dtype)

int_arr = arr.astype(np.int32)
print(int_arr)
print(int_arr.dtype)

# In this example, integers were cast to floating point. If I cast some floating-point numbers to be of integer data type, the decimal part will be truncated:

float64
[ 3 -1 -2  0 12 10]
int32


In [4]:
# If you have an array of strings representing numbers, you can use astype to convert them to numeric form:
import numpy as np

numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=str)  # Best practice in NumPy 2.0
print(numeric_strings.dtype)          # Will show <U4 (Unicode string of length 4)
print(numeric_strings.astype(float))  # Converts strings to floats


<U4
[ 1.25 -9.6  42.  ]


- using another array dtype

   - you can use the dtype of one array to cast another array to the same data type 
   - example in code 

In [3]:
int_array = np.arange(10)  # creates array: [0, 1, 2, ..., 9], dtype=int64 by default
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)  # dtype=float64

int_array.astype(calibers.dtype)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Shorthand dtype codes in NumPy

Instead of typing the full dtype name (like `np.uint32`), NumPy allows you to use **type code strings**:

- `"u4"` means **unsigned 4-byte integer**, which corresponds to `np.uint32`.
- `"i4"` means **signed 4-byte integer**, corresponding to `np.int32`.
- `"f8"` means **8-byte float**, corresponding to `np.float64`.
