### ndarray / multidimensional array :

- ndarray stands for N-dimensional array. It is the core data structure provided by NumPy for storing arrays of any number of dimensions.

- A NumPy ndarray is a homogeneous, multidimensional, contiguous memory array object that stores elements of the same data type.

- This is the primary object used in NumPy to store and operate on data efficiently.

### creating an ndarray 

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])                      # 1D array
arr2 = np.array([[1, 2], [3, 4]])               # 2D array
arr3 = np.array([[[1], [2]], [[3], [4]]])       # 3D array
print(arr1)

[1 2 3]


In [9]:
import numpy as np

a = np.array([[1, 2, 3], [1,2,3]])
print(type(a))  # <class 'numpy.ndarray'>

x =a * 10
print(x)


<class 'numpy.ndarray'>
[[10 20 30]
 [10 20 30]]


### Key properties of ndarray:

- 1.  `.ndim`
   
    - number of dimension of array(axes) 

- 2. `.shape`
   
   - tuple representing the size of each dimension 

- 3. `.size` 
   
   - totsl number of element 

- 4. `.dtype`

   - data type of the element 
   
- 5. `.itemsize`
  
   - size in bytes of each element 

- 6. `.nbytes`

   - total bytes consumes (size * itemsize)             

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)
print(arr.shape)    
print(arr.size)
print(arr.dtype)    
print(arr.itemsize)   
print(arr.nbytes)   


2
(2, 3)
6
int64
8
48


# Why Use `ndarray`?

- **Speed**: Much faster than Python lists due to internal optimizations (C-based).
- **Memory Efficiency**: Uses less memory than a list of lists.
- **Functionality**: Supports a wide range of mathematical, logical, and statistical operations.
- **Broadcasting**: Allows operations on arrays of different shapes.
- **Convenience**: Comes with lots of helpful methods and functions for reshaping, slicing, aggregation, and more.


 ### data type for ndarray

 - The data type or dtype is a special object containing the information (or metadata,
   data about data) the ndarray needs to interpret a chunk of memory as a particular
   type of data:

In [14]:
import numpy as np

arr1 = np.array([1,23,4] , dtype = np.float64)
arr2 = np.array([1,23,4] , dtype = np.int32)
arr3 = np.array([1,23,4] , dtype = np.char43)
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)




AttributeError: module 'numpy' has no attribute 'char43'