### ndarray / multidimensional array :

- ndarray stands for N-dimensional array. It is the core data structure provided by NumPy for storing arrays of any number of dimensions.

- A NumPy ndarray is a homogeneous, multidimensional, contiguous memory array object that stores elements of the same data type.

- This is the primary object used in NumPy to store and operate on data efficiently.

### creating an ndarray 

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])                      # 1D array
arr2 = np.array([[1, 2], [3, 4]])               # 2D array
arr3 = np.array([[[1,2], [2,2]], [[3,2], [4,2]]])       # 3D array
print(arr1)
print(arr3)

[1 2 3]
[[[1 2]
  [2 2]]

 [[3 2]
  [4 2]]]


In [9]:
import numpy as np

a = np.array([[1, 2, 3], [1,2,3]])
print(type(a))  # <class 'numpy.ndarray'>

x =a * 10
print(x)


<class 'numpy.ndarray'>
[[10 20 30]
 [10 20 30]]


### Key properties of ndarray:

- 1.  `.ndim`
   
    - number of dimension of array(axes) 

- 2. `.shape`
   
   - tuple representing the size of each dimension 

- 3. `.size` 
   
   - totsl number of element 

- 4. `.dtype`

   - data type of the element 
   
- 5. `.itemsize`
  
   - size in bytes of each element 

- 6. `.nbytes`

   - total bytes consumes (size * itemsize)             

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)
print(arr.shape)    
print(arr.size)
print(arr.dtype)    
print(arr.itemsize)   
print(arr.nbytes)   


2
(2, 3)
6
int64
8
48


# Why Use `ndarray`?

- **Speed**: Much faster than Python lists due to internal optimizations (C-based).
- **Memory Efficiency**: Uses less memory than a list of lists.
- **Functionality**: Supports a wide range of mathematical, logical, and statistical operations.
- **Broadcasting**: Allows operations on arrays of different shapes.
- **Convenience**: Comes with lots of helpful methods and functions for reshaping, slicing, aggregation, and more.


 ### data type for ndarray

 - The data type or dtype is a special object containing the information (or metadata,
   data about data) the ndarray needs to interpret a chunk of memory as a particular
   type of data:

In [16]:
import numpy as np

arr1 = np.array([1,23,4] , dtype = np.float64)
arr2 = np.array([1,23,4] , dtype = np.int32)
arr3 = np.array([[1,2.2,3],[4,5,6]])
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)




float64
int32
float64


# Data Types (`dtype`) for NumPy `ndarray`

NumPy arrays (`ndarray`) store data of a **single type**. This type is defined by the array's **dtype** (data type), which controls:

- The **kind** of data stored (integer, float, boolean, etc.)
- The **size** in bytes of each element
- How operations on the array elements behave
- The **memory layout** of the array

---

## Why Is `dtype` Important?

1. **Performance**: Using the correct dtype ensures efficient memory usage and fast numerical computations.
2. **Compatibility**: Some operations or libraries expect data in specific dtypes.
3. **Precision**: Different dtypes allow you to control numerical precision and range.
4. **Storage Size**: Smaller dtypes use less memory, which is crucial for large datasets.

---

## NumPy Data Types

### 1. Integer Types (`int` and `uint`)

Integers can be **signed** (positive and negative) or **unsigned** (only positive including zero).

| dtype        | Bytes per element | Range (Signed)                         | Range (Unsigned)                      |
|--------------|-------------------|--------------------------------------|-------------------------------------|
| `np.int8`    | 1                 | -128 to 127                          | N/A                                 |
| `np.uint8`   | 1                 | N/A                                  | 0 to 255                            |
| `np.int16`   | 2                 | -32,768 to 32,767                    | N/A                                 |
| `np.uint16`  | 2                 | N/A                                  | 0 to 65,535                        |
| `np.int32`   | 4                 | -2,147,483,648 to 2,147,483,647     | N/A                                 |
| `np.uint32`  | 4                 | N/A                                  | 0 to 4,294,967,295                  |
| `np.int64`   | 8                 | Very large negative to positive range| N/A                                 |
| `np.uint64`  | 8                 | N/A                                  | Very large positive range            |

**Use cases:**
- Use smaller integer types (`int8`, `int16`) when memory is critical, and data fits within range.
- Use larger types (`int32`, `int64`) for bigger numbers.
- Unsigned integers are useful when data cannot be negative (e.g., pixel values, counts).

---

### 2. Floating-Point Types (`float`)

Floats represent real numbers and can store decimal values.

| dtype        | Bytes per element | Precision                         | Range (approximate)                   |
|--------------|-------------------|---------------------------------|-------------------------------------|
| `np.float16` | 2                 | ~3 decimal digits               | ±6.5×10⁻⁵ to ±6.5×10⁴               |
| `np.float32` | 4                 | ~7 decimal digits               | ±1.5×10⁻⁴⁵ to ±3.4×10³⁸              |
| `np.float64` | 8                 | ~15 decimal digits (default)   | ±5.0×10⁻³²⁴ to ±1.8×10³⁰⁸             |

**Use cases:**
- Use `float32` or `float16` to save memory when precision is less critical (e.g., graphics, ML training).
- Use `float64` (default) for high precision scientific calculations.

---

### 3. Complex Types (`complex`)

Complex numbers consist of a real and an imaginary part, both floats.

| dtype          | Bytes per element | Description                       |
|----------------|-------------------|---------------------------------|
| `np.complex64` | 8                 | 2×32-bit floats (real + imag)   |
| `np.complex128`| 16                | 2×64-bit floats (real + imag)   |

**Use cases:**
- Useful in engineering, physics, and signal processing.

---

### 4. Boolean Type

| dtype        | Bytes per element | Values                         |
|--------------|-------------------|--------------------------------|
| `np.bool_`   | 1                 | `True` or `False`              |

**Use cases:**
- Logical operations, masks, conditions, filters.

---

### 5. String Types

- **Fixed-length ASCII** strings: `np.bytes_`
- **Fixed-length Unicode** strings: `np.str_`

These store fixed-size strings inside the array.

Example:
```python
arr = np.array(['apple', 'banana'], dtype='U6')  # Unicode string with max length 6 
```
### 5. object type 

- **The object data type in NumPy arrays means that the array stores references to arbitrary Python objects instead of fixed-size numerical types like int32 or float64.** 

- **When you create an array with dtype=object, each element can be any Python object: numbers, strings, lists, custom classes, or even mixed types in the same array.**


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4],[1,2,3,4]])
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

# in this example you convert this into int to float 

int64
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]
float64


In [ ]:
import numpy as np
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr.dtype)

int_arr = arr.astype(np.int32)
print(int_arr)
print(int_arr.dtype)

# In this example, integers were cast to floating point. If I cast some floating-point numbers to be of integer data type, the decimal part will be truncated:

float64
[ 3 -1 -2  0 12 10]
int32


In [4]:
# If you have an array of strings representing numbers, you can use astype to convert them to numeric form:
import numpy as np

numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=str)  # Best practice in NumPy 2.0
print(numeric_strings.dtype)          # Will show <U4 (Unicode string of length 4)
print(numeric_strings.astype(float))  # Converts strings to floats


<U4
[ 1.25 -9.6  42.  ]


- using another array dtype

   - you can use the dtype of one array to cast another array to the same data type 
   - example in code 

In [3]:
int_array = np.arange(10)  # creates array: [0, 1, 2, ..., 9], dtype=int64 by default
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)  # dtype=float64

int_array.astype(calibers.dtype)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Shorthand dtype codes in NumPy

Instead of typing the full dtype name (like `np.uint32`), NumPy allows you to use **type code strings**:

- `"u4"` means **unsigned 4-byte integer**, which corresponds to `np.uint32`.
- `"i4"` means **signed 4-byte integer**, corresponding to `np.int32`.
- `"f8"` means **8-byte float**, corresponding to `np.float64`.


# imp point

### NumPy String and Date-Time Types 

- `np.str_` and `np.unicode_`: Unicode strings supporting international characters.
- `np.string_`: ASCII strings limited to basic ASCII characters.
- `np.bytes_` and `np.string_`: Fixed-width byte-encoded strings.
- `np.datetime64`: Represents date and time points.
- `np.timedelta64`: Represents durations or time intervals.
- Useful for efficient date-time and string operations in arrays.
