# ARITHMETIC WITH NUMPY ARRAYS

### Arrays in Python

An **array** is a data structure that stores a collection of elements, usually of the same data type, in a contiguous block of memory. Arrays allow efficient access and manipulation of these elements using indices.

Arrays are important because they enable you to express batch operations on data
without writing any for loops. NumPy users call this vectorization. Any arithmetic
operations between equal-size arrays apply the operation element-wise:

## Arrays in Python

Python does not have a built-in array data type like some other languages (e.g., C or Java). However, Python provides several ways to work with arrays:

### 1. List (Python's built-in sequence)

- The closest built-in Python data structure to an array is the **list**.
- Lists can store elements of different types (not limited to a single type).
- Lists are flexible but not as memory-efficient or fast for numerical computations as arrays in specialized libraries.

Example:
```python
my_list = [1, 2, 3, 4, 5]
print(my_list[0])  # Output: 1


### What is Vectorization?

Arrays are important because they enable you to express **batch operations** on data without writing explicit `for` loops. This process is called **vectorization** in NumPy.

**Vectorization** means performing operations on entire arrays (or large blocks of data) at once, rather than iterating element-by-element with loops. This allows you to write cleaner, faster, and more efficient code.

For example, when you perform arithmetic operations between two arrays of the same size, NumPy applies the operation **element-wise** automatically:

- example 


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b  # Adds elements one by one: [1+4, 2+5, 3+6] -> [5, 7, 9]
print(c)  

[5 7 9]


##### example of arithmetic with numpy array

- 1. basic arithemetic operations 

In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)            
print("Subtraction:", b - a)         
print("Multiplication:", a * b)     
print("Division:", b / a)           
print("Power:", a ** 3) 

Addition: [5 7 9]
Subtraction: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Power: [ 1  8 27]


- 2. broadcasting 
  
   - NumPy supports broadcasting, which lets you perform operations between arrays of different shapes as long as they are compatible.

 

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
c = 10
print(a + c)  # adds 10 to each element of a

# Here, c is a scalar (single value), and NumPy "broadcasts" it to each element of a.

[11 12 13 14]


- 3. multidimensional array arithmetic 
  
  -  Arithmetic works similarly for 2D (or higher) arrays, and the operations are element-wise.

In [12]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])
print(A - B)
print(A + B)
print(A*B)
print(A+3)
print(A - 9)


[[ -9 -18]
 [-27 -36]]
[[11 22]
 [33 44]]
[[ 10  40]
 [ 90 160]]
[[4 5]
 [6 7]]
[[-8 -7]
 [-6 -5]]


- 4. using arithmetic function you can also perform the arithmetic operations 


In [19]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])
print(np.add(A,B))
print("       ")
print(np.subtract(A,B))
print("       ")
print(np.multiply(A,B))
print("       ")
print(np.divide(A,B))
print("       ")
print(np.power(A,2))
print("       ")
print(np.power(B,3))


[[11 22]
 [33 44]]
       
[[ -9 -18]
 [-27 -36]]
       
[[ 10  40]
 [ 90 160]]
       
[[0.1 0.1]
 [0.1 0.1]]
       
[[ 1  4]
 [ 9 16]]
       
[[ 1000  8000]
 [27000 64000]]


- 5. integer division and modulo

In [20]:
a = np.array([5, 10, 15])
b = np.array([2, 3, 4])

print(a // b)  # integer division (floor division)
print(a % b)   # modulo (remainder)


[2 3 3]
[1 1 3]


#### Key point 

- Arithmetic operations do not change the original arrays unless you explicitly assign the result.

In [1]:
c = a + b  # a and b remain unchanged


NameError: name 'a' is not defined

- Operations between arrays of different sizes that cannot be broadcast will raise an error.

- If one array has floats and the other has integers, the result will be upcast to floats to preserve precision.