# Indexing and slicing 

- Indexing allows you to access a single element of the array.

- Slicing allows you to access a range or subset of elements.

- Works similarly to Python lists but is much more powerful in NumPy (especially for multidimensional arrays).

- example 

In [12]:
import numpy as np 
arr = np.arange(10)
print(arr)
print("index element of the given index " ,arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)
# An important first distinction from Python’s built-in lists is that
# array slices are views on the original array. This means that the data
# is not copied, and any modifications to the view will be reflected in
# the source array

arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 123454
print(arr)
print(arr[:])

[0 1 2 3 4 5 6 7 8 9]
index element of the given index  5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[     0      1      2      3      4     12 123454     12      8      9]
[     0      1      2      3      4     12 123454     12      8      9]


## 1D array


- indexing 

In [14]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a[0])     # 10
print(a[-1])    # 50 (last element)
# Works like Python lists.

# Indexing starts from 0.

# Negative indices access from the end.


10
50


- slicing
  
  - syntax
    - ``` [start:stop:step] ```
    - Start: inclusive
    - Stop: exclusive
    - Step: how many to skip 

In [ ]:
a = np.array([10, 20, 30, 40, 50])

print(a[1:4])     
print(a[:3])      
print(a[::2])    


[20 30 40]
[10 20 30]
[10 30 50]


## 2D array

- indexing and slicing in 2D array

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Single element access
print(b[0, 1])     # 2 (row 0, column 1)
print(b[2][2])     # 9 (same thing, different style)

# Row access
print(b[1])        # [4 5 6]

# Column access
print(b[:, 1])     # [2 5 8] (all rows, column 1)

# Sub-matrix
print(b[0:2, 1:3])
                   


2
9
[4 5 6]
[2 5 8]
[[2 3]
 [5 6]]


  - row access and column access in ndarray

1. row access
  
  - ```a[row index] ```

In [ ]:
# access a single row
import numpy as np

a = np.array([
    [1, 2, 3],    # Row 0
    [4, 5, 6],    # Row 1
    [7, 8, 9]     # Row 2
    ])
print(a[2])



[7 8 9]


In [23]:
# access a multiple row 
import numpy as np

a = np.array([
    [1, 2, 3],    # Row 0
    [4, 5, 6],    # Row 1
    [7, 8, 9]     # Row 2
])
print(a[0:2])
print(a[:-2])

[[1 2 3]
 [4 5 6]]
[[1 2 3]]


In [24]:
# fancy row access 
import numpy as np

a = np.array([
    [1, 2, 3],    # Row 0
    [4, 5, 6],    # Row 1
    [7, 8, 9]     # Row 2
])
print(a[[2,1]])

[[7 8 9]
 [4 5 6]]


2. column access 
   - ```a[:,column index] ```

In [25]:
import numpy as np

a = np.array([
    [1, 2, 3],    # Row 0
    [4, 5, 6],    # Row 1
    [7, 8, 9]     # Row 2
])
# access single column
print(a[:, 0])  # First column → [1 4 7]
print(a[:, 1])  # Second column → [2 5 8]
# access multiple column
print(a[:, [0, 2]])  # First and third columns

[1 4 7]
[2 5 8]
[[1 3]
 [4 6]
 [7 9]]


3. slicing both rows and column
   - ```a[row_start:row_stop, col_start:col_stop] ```

2 x 2

In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3],    # Row 0
    [4, 5, 6],    # Row 1
    [7, 8, 9]     # Row 2
])

print(a[0:2 , 0:2])


[[1 2]
 [4 5]]
[[5]]


2 x 2 center element 

In [32]:
import numpy as np

a = np.array([
    [10, 20, 30, 40],   # Row 0
    [50, 60, 70, 80],   # Row 1
    [90, 100, 110, 120],# Row 2
    [130, 140, 150, 160]# Row 3
])
print(a[1:3 , 1:3])
print(a[2:4 , 2:4])

[[ 60  70]
 [100 110]]
[[110 120]
 [150 160]]


Select last 3 columns of the first 2 rows

In [33]:
import numpy as np

a = np.array([
    [10, 20, 30, 40],   # Row 0
    [50, 60, 70, 80],   # Row 1
    [90, 100, 110, 120],# Row 2
    [130, 140, 150, 160]# Row 3
])
print(a[0:2 , 1:4])

[[20 30 40]
 [60 70 80]]


Select every row but only first and last column



In [44]:
import numpy as np

a = np.array([
    [10, 20, 30, 40],   # Row 0
    [50, 60, 70, 80],   # Row 1
    [90, 100, 110, 120],# Row 2
    [130, 140, 150, 160]# Row 3
])
print(a[0:4 , [0,3]]) # either only : print all the rows
print(a[:,[0,-1]])

[[ 10  40]
 [ 50  80]
 [ 90 120]
 [130 160]]
[[ 10  40]
 [ 50  80]
 [ 90 120]
 [130 160]]


Select every 2nd row and 2nd column using steps


In [2]:
import numpy as np

a = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])
print(a[::2 , ::2])

[[ 1  3]
 [ 9 11]]


Pick rows [0, 2] and then from those pick columns 1 & 3:


In [ ]:
arr[np.ix_([0, 2], [1, 3])]

array([[ 2,  4],
       [10, 12]])

Pick a checkerboard pattern of size 4×4 (even rows & odd columns only):

In [6]:
import numpy as np

a = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])
print(a[1:3 , 1:3])

[[ 6  7]
 [10 11]]


### refrennce table
| What you want                                 | NumPy syntax               | Result/Explanation                                             |
|----------------------------------------------|----------------------------|----------------------------------------------------------------|
| Single row, e.g. row 2                        | `arr[2]`                   | 1D array of shape (4,) → `[90, 100, 999, 120]`                 |
| Single column, e.g. col 0                     | `arr[:, 0]`                | 1D array → `[10, 0, 90, 130]`                                  |
| Slice of rows 1–3                             | `arr[1:4]`                 | rows 1, 2, 3 → shape (3×4)                                     |
| Slice of cols 0–2                             | `arr[:, 0:3]`              | cols 0, 1, 2 → shape (4×3)                                     |
| Every other row                               | `arr[::2]`                 | rows 0, 2 → shape (2×4)                                        |
| Every other column                            | `arr[:, ::2]`              | cols 0, 2 → shape (4×2)                                        |
| Last row                                      | `arr[-1]`                  | same as `arr[3]`                                               |
| Last column                                   | `arr[:, -1]`               | same as `arr[:, 3]`                                            |
| Fancy pick rows 2, 0, 3                       | `arr[[2, 0, 3]]`           | Reordered array of shape (3×4)                                |
| Fancy pick cols 3, 1                          | `arr[:, [3, 1]]`           | shape (4×2), columns 3 & 1 in that order                      |
| Corresponding elements (0,1), (2,3)           | `arr[[0,2],[1,3]]`         | 1D array → `[arr[0,1], arr[2,3]]`                             |
| Submatrix rows 1–2, cols 2–3                  | `arr[1:3, 2:4]`            | shape (2×2) → picks those 4 elements                          |
| Boolean select rows where col 0 > 50          | `arr[arr[:,0]>50]`         | shape (2×4) → rows 2 & 3                                      |
| Boolean select columns where row 3 < 160      | `arr[:, arr[3,:]<160]`     | shape (4×3) → cols 0, 1, 2                                    |
