# boolean Indexing

- Boolean Indexing means selecting elements from a NumPy array using True/False values (i.e., Boolean values).

- It allows us to filter arrays based on conditions.

- boolean array must be of same length  

### Why is it useful?
- It helps when:

  - You want only specific values from an array (e.g., all elements greater than 10).

  - You want to modify certain elements conditionally.

In [ ]:
# in 1D array
import numpy as np

arr = np.array([5, 10, 15, 20, 25])

# Condition: select elements greater than 10
bool_index = arr > 10
print(bool_index)


[False False  True  True  True]


In [5]:
# in 2D array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Find all elements > 4
print(arr2d[arr2d > 4])


[5 6 7 8 9]


In [ ]:
# comparison using boolean
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[1,2],[3,4],[5,6]])

print(b > a)
print(a == b)
print(a > b)
# check all the elements are equal
np.array_equal(a,b)

# Using np.all() and np.any()
print(np.all(a==b))

print(np.any(a!=b)) # any element match


[[False False]
 [False False]
 [False False]]
[[ True  True]
 [ True  True]
 [ True  True]]
[[False False]
 [False False]
 [False False]]
True
False


In [28]:
# compairing two array
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 5], [3, 0]])

# Element-wise
print(a == b)


[[ True False]
 [ True False]]


In [29]:
# broadcast comparisioin 
a = np.array([10, 20, 30])
b = 20

print(a > b)   # [False False  True]


[False False  True]


using boolean array

- You can also use a manually created Boolean array to select values:


In [2]:
import numpy as np 
name = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12,-4], [3,4]])

print(name)
print(data)

print(name=="Bob")
print(data[name=="Bob"])
print(name !="Bob")
print(data[~(name == "Bob")])
# The ~ operator can be useful when you want to invert a Boolean array referenced by avariable ~(bitwise NOT operator)
cond = name == "Bob"
print(data[~cond])


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]
[ True False False  True False False False]
[[4 7]
 [0 0]]
[False  True  True False  True  True  True]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]
[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


To select two of the three names to combine multiple Boolean conditions, use
Boolean arithmetic operators like & (and) and | (or)

In [12]:
import numpy as np 
name = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12,-4], [3,4]])

print(name)
print(data)
mask = (name == "Bob") | (name == "Will")
print(mask)
print(data[mask])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]
[ True False  True  True  True False False]
[[ 4  7]
 [-5  6]
 [ 0  0]
 [ 1  2]]


In [16]:
import numpy as np 
name = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12,-4], [3,4]])
# you can also assign a value using boolean indexing 
data[data <0] = 0
print(data)

# You can also set whole rows or columns using a one-dimensional Boolean array
data[name != "Joe"] = 7
print(data)

[[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]
 [0 0]
 [3 4]]
[[7 7]
 [0 2]
 [7 7]
 [7 7]
 [7 7]
 [0 0]
 [3 4]]


combine condition

- Use logical operators:

- & for AND

- | for OR

- ~ for NOT

In [4]:
arr = np.array([5, 10, 15, 20, 25])

# Select elements > 10 and < 25
print(arr[(arr > 10) & (arr < 25)])  # [15 20]


[15 20]


modifying element using boolean indexing 

In [5]:
arr = np.array([10, 20, 30, 40, 50])

# Change all values > 30 to 0
arr[arr > 30] = 0

print(arr)


[10 20 30  0  0]


# Fanncy indexing 

 - Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
 
 - it lets you access or modify multiple elements of an array using arrays or lists of indices, instead of slices.
 
 - Fancy indexing means using integer arrays or boolean arrays to access or modify specific elements in a NumPy array.  

In [21]:
arr = np.zeros((8,5))
for i in range(8):
    arr[i] = i
print(arr)
print("   ")
indexes = [4,3,0,6]
result = arr[indexes]
print(result)
print("  ")
# you can use negatve indexing selct rows from the end 
nindexes = [-3,-5,-7]
result1 = arr[nindexes]
print(result1)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7.]]
   
[[4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3.]
 [0. 0. 0. 0. 0.]
 [6. 6. 6. 6. 6.]]
  
[[5. 5. 5. 5. 5.]
 [3. 3. 3. 3. 3.]
 [1. 1. 1. 1. 1.]]


In [7]:
import numpy as np
arr = np.arange(32).reshape((8,4))
print(arr)

print(" ")
array= arr[[1, 5, 7, 2], [0, 3, 1, 2]]
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
 
[ 4 23 29 10]


here the element is like (rows, column) (1.0),(5,3),(7,1),(2,2)