# boolean Indexing

- Boolean Indexing means selecting elements from a NumPy array using True/False values (i.e., Boolean values).

- It allows us to filter arrays based on conditions.

- boolean array must be of same length  

### Why is it useful?
- It helps when:

  - You want only specific values from an array (e.g., all elements greater than 10).

  - You want to modify certain elements conditionally.

In [ ]:
# in 1D array
import numpy as np

arr = np.array([5, 10, 15, 20, 25])

# Condition: select elements greater than 10
bool_index = arr > 10
print(bool_index)


[False False  True  True  True]


In [5]:
# in 2D array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Find all elements > 4
print(arr2d[arr2d > 4])


[5 6 7 8 9]


In [ ]:
# comparison using boolean
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[1,2],[3,4],[5,6]])

print(b > a)
print(a == b)
print(a > b)
# check all the elements are equal
np.array_equal(a,b)

# Using np.all() and np.any()
print(np.all(a==b))

print(np.any(a!=b)) # any element match


[[False False]
 [False False]
 [False False]]
[[ True  True]
 [ True  True]
 [ True  True]]
[[False False]
 [False False]
 [False False]]
True
False


In [28]:
# compairing two array
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 5], [3, 0]])

# Element-wise
print(a == b)


[[ True False]
 [ True False]]


In [29]:
# broadcast comparisioin 
a = np.array([10, 20, 30])
b = 20

print(a > b)   # [False False  True]


[False False  True]


using boolean array

- You can also use a manually created Boolean array to select values:


In [3]:
import numpy as np 
name = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12,-4], [3,4]])

print(name)
print(data)

print(name=="Bob")
print(data[name=="Bob"])

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]
[ True False False  True False False False]
[[4 7]
 [0 0]]


combine condition

- Use logical operators:

- & for AND

- | for OR

- ~ for NOT

In [9]:
arr = np.array([5, 10, 15, 20, 25])

# Select elements > 10 and < 25
print(arr[(arr > 10) & (arr < 25)])  # [15 20]


[15 20]


modifying element using boolean indexing 

In [10]:
arr = np.array([10, 20, 30, 40, 50])

# Change all values > 30 to 0
arr[arr > 30] = 0

print(arr)


[10 20 30  0  0]
