## Array manipulation 

- Array manipulation means changing the structure, shape, or contents of a NumPy array without changing the actual data.

- Reshaping is a part of this — it means changing the number of rows and columns in an array.

- syntax :
   ``` np.reshape(array, new_shape) ``` OR ``` array.reshape(new_shape) ```

### Why Is It Useful?
- To prepare data for machine learning models.

- To perform operations like matrix multiplication.

- To transform data into a desired format (like from 1D to 2D or 3D).

### 1. reshape():

- change the shape

In [1]:
import numpy as np

a = np.arange(6)   # [0, 1, 2, 3, 4, 5]
b = a.reshape((2, 3))
print(b)


[[0 1 2]
 [3 4 5]]


### 2. ravle() and flatten()

- both are used to change multidimensional array into 1D array 

- ravel() – returns a view (affects original if modified)

- flatten() – returns a copy (original is unchanged)

In [2]:
a = np.array([[1, 2], [3, 4]])
print(a.ravel())     # [1 2 3 4]
print(a.flatten())   # [1 2 3 4]


[1 2 3 4]
[1 2 3 4]


### 3. transpose()

- it changes the rows to column and column to rows 

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)


[[1 4]
 [2 5]
 [3 6]]


### 4. reshape(-1)

- Use -1 when you don’t want to manually calculate one of the dimensions:



In [4]:
a = np.arange(12)
b = a.reshape(3, -1)   # NumPy figures out that it must be (3, 4)
print(b)
# in this code 3 rows want and the number of the column is automatically fined by numpy

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
import numpy as np

a = np.arange(12)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
b = a.reshape(-1,4) # here number of column is 4 and no. of rows is fined by numpy 
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 5. resize() vs reshape() 

- resize() changes the array in place and can also increase size by filling with zeros:

In [ ]:
a = np.array([1, 2, 3])
a.resize((2, 3))
print(a)


In [6]:
a = np.array([1, 2, 3])
a.resize((2, 4))
print(a)
# here you have 3 value in array and you want 2x4= 8 then three value is puted and rest of the data is fill with zero

[[1 2 3 0]
 [0 0 0 0]]


### swapaxes() 

- swap the axes of the array 
- it is also like transpose but it is mainly useful for 3D array 

In [ ]:
a = np.array([[[1,2],[3,4]]])
b = np.swapaxes(a, 0, 2)


In [7]:
# 3D 
a = np.array([[[1, 2], [3, 4]]])
# shape = (1, 2, 2)

b = np.swapaxes(a, 0, 2)
print(b.shape)


(2, 2, 1)
