### transposing 

- flipping rows into column and column into row
- example 

In [5]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
array = arr.T
print(array)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
arr = np.arange(15).reshape((3,5))
print(arr)
array = arr.T
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [27]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(arr)
array = np.dot(arr.T , arr)
print(array)
# in place of .dot you can use infix operator @
array1 = arr.T @ arr
print(array1)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
[[39 20 12]
 [20 14  2]
 [12  2 10]]
[[39 20 12]
 [20 14  2]
 [12  2 10]]


#  Matrix Computation

Matrix computation means performing **mathematical operations** on matrices.

A **matrix** is simply a 2D table of numbers.  
Example:
 - addtion and substraction
 - matrix multiplication(dot product)
 - transpose of matrix
 - inverse of matrix 
 - determinant of matrix



In [ ]:
# addtion and subtraction
A = [[1, 2],
     [3, 4]]
B = [[5, 6],
     [7, 8]]

A + B 


[[1, 2], [3, 4], [5, 6], [7, 8]]

In [14]:
# dot product
A = [[1, 2],
     [3, 4]]
B = [[5, 6],
     [7, 8]]

np.dot(A,B)


array([[19, 22],
       [43, 50]])

In [17]:
# transpose
arr = np.arange(15).reshape((3,5))
print(arr)
array = arr.T
print(array)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


inverse of matrix
 - Only square matrices (like 2x2, 3x3) can have an inverse.
 
 - It’s like the reciprocal of a matrix.

In [23]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
inv = np.linalg.inv(A)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


determinant of the matrix

 - A single number that gives info about the matrix (like invertibility).

In [21]:
np.linalg.det(A)


np.float64(-2.0000000000000004)

### swapping

- Transposing is a special case of swapping axes for 2D arrays. But in higher-dimensional arrays (3D, 4D, etc.),        swapping axes gives you more control.
- example 


In [33]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
array = arr.swapaxes(0,1)
print(array)
print(arr)

[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]
[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
