## stacking array

- Stacking means joining multiple arrays (of the same shape) along a new axis.

### There are different ways to stack:

- Vertically (row-wise) 📚

- Horizontally (column-wise) 🧱

- Depth-wise (like layers)

- using stack to add new axes 


#### Prerequisites: Shape Rules
Before stacking, arrays must have:

- Same shape (except in the axis you're stacking along)

- Mostly same dimensions (e.g., both 2D or both 1D)

### common stacking function


## 1 . vstack() 

- Stacks arrays vertically (along rows)
- Rows increase, columns remain same

- upar se niche 

In [2]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.vstack((a,b))
print(c)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 2. hstack() 

- horizontal stack (column wise)

- Stacks arrays horizontally (along columns)

- Columns increase, rows remain same 

In [4]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.hstack((a,b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


## 3. dstack() 

- depth stacking (3D stacking)

- Stacks arrays along a new third axis (depth)
- Like adding layers

In [5]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.dstack((a,b))
print(c)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## 4. stack()

- stack along new axis (custom axis)

- you can stack along any axis using ```np.stack()```

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.stack((a,b),axis=0) # axis 0 means rows wise like vstack
d = np.stack((a,b),axis=1) # axis 1 measn column wise like hstack
print(c)
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


## 5.  concatenate() – Flexible Way

- similar like ```np.stack()```

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.concatenate((a, b), axis=0)  # rows
print(result)
result1 = np.concatenate((a, b), axis=1)  # columns
print(result1)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## 6. np.column_stack(): Stack as columns (2D)


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.column_stack((a, b))
print(result)


[[1 4]
 [2 5]
 [3 6]]


## 7. np.row_stack(): Stack row-wise (Like vstack)

In [15]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.row_stack((a, b))


/tmp/ipykernel_17782/409142956.py:4: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  result = np.row_stack((a, b))


# spliting array :

- it is the opposite of stacking of array 
- in this we divide a one numpy array into multi sub-array

- Just like slicing, but here we break the array into chunks — either equal or specified sizes.

 

### common types of splitting function 

## 1. np.split()

- splitting array into equal parts

- syntax:
  - ``` np.split(array, indices_or_sections, axis=0)``` 

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
result = np.split(a, 3)
print(result)
# it splits array into three rqual parts
# if the parts is not equal it will raise an error 

[array([1, 2]), array([3, 4]), array([5, 6])]


## 2. np.array_split(array , num_split)

- this is more flexible - it allows unequal split 

In [ ]:
a = np.array([1, 2, 3, 4, 5])
result = np.array_split(a, 3)
print(result)
# useful when array size is not perfectlt divisible 

[array([1, 2]), array([3, 4]), array([5])]


##  np.hsplit(array, num_splits): Horizontal Split (axis=1)

- Splits columns of a 2D array.

In [20]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

result = np.hsplit(a, 2)
print(result)


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


## 4.  np.vsplit(array, num_splits): Vertical Split (axis=0)

- Splits rows of a 2D array.

In [22]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

result = np.vsplit(a, 2)

print(result)


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


## np.dsplit(array, num_splits): Depth-wise Split (axis=2)

- Used for 3D arrays.

In [23]:
a = np.array([[[1, 2, 3],
               [4, 5, 6]]])

result = np.dsplit(a, 3)
print(result)

[array([[[1],
        [4]]]), array([[[2],
        [5]]]), array([[[3],
        [6]]])]


## Common Errors to Avoid

| **Mistake**                           | **What Happens**                  |
|--------------------------------------|-----------------------------------|
| Using `split` when array not divisible | ❌ Raises `ValueError`             |
| Wrong `axis`                          | ❌ Unexpected output shape         |
| Not using 3D array with `dsplit`      | ❌ `ValueError`                   |
