## stacking array

- Stacking means joining multiple arrays (of the same shape) along a new axis.

### There are different ways to stack:

- Vertically (row-wise) 📚

- Horizontally (column-wise) 🧱

- Depth-wise (like layers)

- using stack to add new axes 


#### Prerequisites: Shape Rules
Before stacking, arrays must have:

- Same shape (except in the axis you're stacking along)

- Mostly same dimensions (e.g., both 2D or both 1D)

### common stacking function


## 1 . vstack() 

- Stacks arrays vertically (along rows)
- Rows increase, columns remain same

- upar se niche 

In [2]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.vstack((a,b))
print(c)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 2. hstack() 

- horizontal stack (column wise)

- Stacks arrays horizontally (along columns)

- Columns increase, rows remain same 

In [4]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.hstack((a,b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


## 3. dstack() 

- depth stacking (3D stacking)

- Stacks arrays along a new third axis (depth)
- Like adding layers

In [5]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.dstack((a,b))
print(c)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## 4. stack()

- stack along new axis (custom axis)

- you can stack along any axis using ```np.stack()```

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.stack((a,b),axis=0) # axis 0 means rows wise like vstack
d = np.stack((a,b),axis=1) # axis 1 measn column wise like hstack
print(c)
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


## 5.  concatenate() – Flexible Way

- similar like ```np.stack()```

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.concatenate((a, b), axis=0)  # rows
print(result)
result1 = np.concatenate((a, b), axis=1)  # columns
print(result1)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## 6. np.column_stack(): Stack as columns (2D)


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.column_stack((a, b))
print(result)


[[1 4]
 [2 5]
 [3 6]]


## 7. np.row_stack(): Stack row-wise (Like vstack)

In [15]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.row_stack((a, b))


/tmp/ipykernel_17782/409142956.py:4: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  result = np.row_stack((a, b))
