 # Adding and removing axis 

- To convert 1D to 2D, or 2D to 3D, and vice versa

- To prepare data for models, images, or batch processing

### Adding axis :

- we add axis using :
  
  - ```np.expand_dims()``` - to add axis at a specific position 
  
  - ```array[np.newaxis, :]``` - adding using slicing (shortcut) 

  - ```reshape()``` - adding axis by manually reshaping 

### ```np.expand_dims()``` method


In [3]:
import numpy as np

a = np.array([1, 2, 3])
print(a.shape)  # (3,)

b = np.expand_dims(a, axis=0)  # Adds a new axis at position 0
print(b.shape) # (1, 3)
print(b)  

c = np.expand_dims(a, axis=1)
print(c.shape) #(3,1)
print(c)


(3,)
(1, 3)
[[1 2 3]]
(3, 1)
[[1]
 [2]
 [3]]


### ```np.newaxis``` method

In [9]:
import numpy as np
a = np.array([1,2,3])
print(a.shape)

b = a[np.newaxis,:] # (1,3) it is similar to axis = 0
c = a[:,np.newaxis] # (3,1) and it is similar to axis = 1
print(b)
print(c)

(3,)
[[1 2 3]]
[[1]
 [2]
 [3]]


## ```reshape() ``` method 

- you can reshape to chnage dimension

In [ ]:
a = np.array([1, 2, 3])

b = a.reshape(1, 3)  # (1, 3)
c = a.reshape(3, 1)  # (3, 1)
print(b)
print(c)
# only use reshape when you sure about the size of array


[[1 2 3]]
[[1]
 [2]
 [3]]


### removing axis 

- to remove unecessary dimensions (like (1,2,3) -> (3,):)

- we remove using 
  
  - ```np.sqeeze()```
  
  - ```reshape()```   

## ```np.sqeeze()``` method

In [12]:
a = np.array([[[1, 2, 3]]])   # shape: (1, 1, 3)
b = np.squeeze(a)
print(b.shape)  # (3,)
# you can specify which axes to remove 
c = np.array([[[1, 2, 3]]])   # shape: (1, 1, 3)
d = np.squeeze(c, axis=0)     # removes axis 0 → shape (1, 3)
print(d)



(3,)
[[1 2 3]]


## ```reshape()`` method

In [13]:
a = np.array([[[1, 2, 3]]])   # shape: (1, 1, 3)
b = a.reshape(3,)
print(b.shape)  # (3,)


(3,)
